version: '3'
services:
  app:
    container_name: springboot-postgresql
    image: springboot-postgresql
    build: ./
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=test